name: Create Azure Machine Learning workspace

on:
  # C:\Local-Projects\AI-in-a-Box\1-machine-learning\src\model
  push:
    branches:
     - 'main'
    paths:
    - 'src/model/*'
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-dev-mlops'
        type: string
      aml_workspace:
        description: 'Azure Machine Learning workspace name'
        required: true
        default: 'mlw-dev-mlops'
        type: string

env:
  rg: '****'
  amlw: '****'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Define rg and amlw
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "rg=${{ env.rg }}" >> "$GITHUB_ENV"
          echo "amlw=${{ env.amlw }}" >> "$GITHUB_ENV"
        else
          echo "rg=${{ github.event.inputs.resource_group }}" >> "$GITHUB_ENV"
          echo "amlw=${{ github.event.inputs.aml_workspace }}" >> "$GITHUB_ENV"
        fi
        echo "The value of rg is -- ${{ env.rg }}"
        echo "The value of amlw is -- ${{ env.amlw }}"
    - name: Print
      run: |
        echo "The value of rg is -- ${{ env.rg }}"
        echo "The value of amlw is -- ${{ env.amlw }}"
