name: Publisher

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      #Get the code files from the repo
      - uses: actions/checkout@v3
      # Publish the module to the PowerShell Gallery
      - name: PowerShell Gallery Publisher
        shell: pwsh
        run: |
          Write-Output "The line bellow is a dir:"
          dir
          Write-Output "Our value for GITHUB_REF is: ${{ env.GITHUB_REF }}"
          Write-Output "Our value for env:GITHUB_REF is: $env:GITHUB_REF"
          Write-Output "The live bellow is all env variables:"
          Get-ChildItem env: